#!/bin/bash
if [ -z "$(ls -A /lib410/Resources/neon/plugins/installed)" ]; then
   echo "No extensions are installed."
else
   ls -A /lib410/Resources/neon/plugins/installed
   echo "Execute: "
   read exec
   if [ -z $(ls /lib410/Resources/neon/plugins/installed|grep $exec) ]; then
   	echo "No such extension found."
   else
      cmdlocation=$(</lib410/Resources/neon/plugins/installed/$exec)
      $cmdlocation
   fi
fi