#!/bin/bash
STORAGE=/private/var/mobile/neonutil_backups
cd $STORAGE
echo "DEB Backups---------------"
if [[ -e *.ndebbackup ]]; then
	ls *.ndebbackup
else
	echo "  No backups."
fi
echo "Preference Backups--------"
if [[ -e *.nprefbackup ]]; then
	ls *.nprefbackup
else
	echo "  No backups."
fi
echo "Source List Backups-------"
if [[ -e *.nsrcbackup ]]; then
	ls *.nsrcbackup
else
	echo "  No backups."
fi
echo "Master Backups------------"
if [[ -e *.nmasbackup ]]; then
	ls *.nmasbackup
else
	echo "  No backups."
fi
echo "--------------------------"