#!/bin/bash
STORAGE=/private/var/mobile/neonutil_backups
echo "DEB Backups---------------"
if [ -e /private/var/mobile/neonutil_backups/*.ndebbackup ]; then
	ls /private/var/mobile/neonutil_backups/*.ndebbackup
else
	echo "  No backups."
fi
echo "Preference Backups--------"
if [ -e /private/var/mobile/neonutil_backups/*.nprefbackup ]; then
	ls /private/var/mobile/neonutil_backups/*.nprefbackup
else
	echo "  No backups."
fi
echo "Source List Backups-------"
if [ -e /private/var/mobile/neonutil_backups/*.nsrcbackup ]; then
	ls /private/var/mobile/neonutil_backups/*.nsrcbackup
else
	echo "  No backups."
fi
echo "Master Backups------------"
if [ -e /private/var/mobile/neonutil_backups/*.nmasbackup ]; then
	ls /private/var/mobile/neonutil_backups/*.nmasbackup
else
	echo "  No backups."
fi
echo "--------------------------"