#!/bin/bash
name=$1
interaction=$2
override=$3
log=/lib410/Resources/neon/plugins/log-debbackup
if [[ $interaction ]]; then
	if [[ $name ]]; then
		echo "START_EXTRACTION" > $log
		echo "1/4: Extracting DEBs..."
		if [[ $override ]]; then
			echo "START_EXTRACTION_LIMIT_OVERRIDE" > $log
			echo "  !!Override limitation detected. This may cause reboot!!"
			/lib410/Resources/neon/plugins/exec/clone_deb --override
		else
			/lib410/Resources/neon/plugins/exec/clone_deb
		fi
		echo "CLEAN_EXTRACTOR_LOG" > $log
		rm /lib410/Resources/neon/plugins/log-debextract
		echo "2/4: Filtering..."
		echo "START_FILTERING" > $log
		/lib410/Resources/neon/plugins/exec/filter_deb
		echo "3/4: Compressing..."
		echo "START_COMPRESSING" > $log
		cd /lib410/Resources/neon/temp
		zip -rqq $name.ndebbackup deb-backup
		mv $name.ndebbackup /private/var/mobile/neonutil_backups/$name.ndebbackup
		echo "4/4: Cleaning up..."
		echo "START_CLEANUP" > $log
		/lib410/Resources/neon/cleanup debian
		echo "Done!"
		rm $log
	else
		echo "Error:"
		echo "Process backup_deb returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [[ -z $name ]]; then
		echo "Name cannot be empty!"
	else
		echo "START_EXTRACTION" > $log
		echo "1/4: Extracting DEBs..."
		if [[ $override ]]; then
			echo "START_EXTRACTION_LIMIT_OVERRIDE" > $log
			echo "  !!Override limitation detected. This may cause reboot!!"
			/lib410/Resources/neon/plugins/exec/clone_deb --override
		else
			/lib410/Resources/neon/plugins/exec/clone_deb
		fi
		echo "CLEAN_EXTRACTOR_LOG" > $log
		rm /lib410/Resources/neon/plugins/log-debextract
		echo "2/4: Filtering..."
		echo "START_FILTERING" > $log
		/lib410/Resources/neon/plugins/exec/filter_deb
		echo "3/4: Compressing..."
		echo "START_COMPRESSING" > $log
		cd /lib410/Resources/neon/temp
		zip -rqq $name.ndebbackup deb-backup
		mv $name.ndebbackup /private/var/mobile/neonutil_backups/$name.ndebbackup
		echo "4/4: Cleaning up..."
		echo "START_CLEANUP" > $log
		/lib410/Resources/neon/cleanup debian
		echo "Done!"
		rm $log
	fi
fi
