#!/bin/bash
name=$1
interaction=$2
if [[ $interaction ]]; then
	if [[ $name ]]; then
		echo "1/4: Extracting DEBs..."
		/lib410/Resources/neon/plugins/exec/clone_deb
		echo "2/4: Filtering..."
		/lib410/Resources/neon/plugins/exec/filter_deb
		echo "3/4: Archiving..."
		zip -rqq /private/var/mobile/neonutil_backups/$name.ndebbackup /lib410/Resources/neon/temp/deb-backup
		echo "4/4: Cleaning up..."
		/lib410/Resources/neon/cleanup debian
		echo "Done!"
	else
		echo "Error:"
		echo "Process backup_deb returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [[ -z $name ]]; then
		echo "Name cannot be empty!"
	else
		echo "1/4: Extracting DEBs..."
		/lib410/Resources/neon/plugins/exec/clone_deb
		echo "2/4: Filtering..."
		/lib410/Resources/neon/plugins/exec/filter_deb
		echo "3/4: Archiving..."
		zip -rqq /private/var/mobile/neonutil_backups/$name.ndebbackup /lib410/Resources/neon/temp/deb-backup
		echo "4/4: Cleaning up..."
		/lib410/Resources/neon/cleanup debian
		echo "Done!"
	fi
fi
