#!/bin/bash
if [ ! -e "/private/var/mobile/neonutil_backups" ]; then
	echo "Backup storage does not exist. Making one..."
	mkdir /private/var/mobile/neonutil_backups
else
	echo "Backup storage already exists. No need to make one."
fi 
if [ ! -e "/private/var/mobile/neonutil_backups/localsnapshots" ]; then
	echo "Backup snapshot storage does not exist. Making one..."
	mkdir /private/var/mobile/neonutil_backups/localsnapshots
else
	echo "Backup snapshot storage already exists. No need to make one."
fi 