#!/bin/bash
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-core") ]]; then
	echo "Failed to verify core. Please use the official core."
	exit
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-interface") ]]; then
	echo "Failed to verify interface. Please use the official interface."
	exit
fi
if [ -e /lib410/Resources/neon/plugins/tpload ]; then
	echo "Depreicated extension loader detected."
	echo "Please remove: com.nvtechnology.neonutil-tpload"
	exit
fi
/lib410/Resources/neon/loader $1 $2 $3 $4