#!/bin/bash
execute=$1
args=$2
interaction=$3
coredirect=$4
ROOT=/lib410/Resources/neon/plugins/exec
if [ $execute == "-backup-deb" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-debbackup") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/backup_deb $args $interaction $coredirect
	fi
elif [ $execute == "-backup-pref" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-prefbackup") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/backup_pref $args $interaction $coredirect
	fi
elif [ $execute == "-restore-deb" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-debrestore") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/restore_deb $args $interaction $coredirect
	fi
elif [ $execute == "-restore-pref" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-prefrestore") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/restore_pref $args $interaction $coredirect
	fi
elif [ $execute == "-cydiafix" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-cydiafixer") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/cydiafixer $interaction
	fi
elif [ $execute == "-backup-m" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-masterbackup") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/backup_master $args $interaction $coredirect
	fi
elif [ $execute == "-restore-m" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-masterrestore") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/restore_master $args $interaction $coredirect
	fi
elif [ $execute == "-backup-src" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-sourcebackup") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/backup_source $args $interaction $coredirect
	fi
elif [ $execute == "-restore-src" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-sourcerestore") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/restore_source $args $interaction $coredirect
	fi
elif [ $execute == "-list" ]; then
	if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-backuplist") ]]; then
		echo "It seems plugin is not installed. Please install it using Cydia."
	else
		$ROOT/list
	fi
else
	echo "Error:"
	echo "Process 'querynlink' returned error."
	echo $execute "is not a supported plugin."
fi