#!/bin/bash
ROOT=/lib410/Resources/neon
BACK_DEB="notinstalled"
BACK_PREF="notinstalled"
BACK_SRC="notinstalled"
BACK_M="notinstalled"
RESTORE_DEB="notinstalled"
RESTORE_PREF="notinstalled"
RESTORE_SRC="notinstalled"
RESTORE_M="notinstalled"
FIX_CYDIA="notinstalled"
extload="installed"
echo "NEON UTILITY INTERFACE"
echo "----------------------"
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-debbackup") ]]; then
	echo "1. Backup Debian Packages [NI]"
else
	echo "1. Backup Debian Packages"
	BACK_DEB="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-prefbackup") ]]; then
	echo "2. Backup Preference Files [NI]"
else
	echo "2. Backup Preference Files"
	BACK_PREF="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-sourcebackup") ]]; then
	echo "3. Backup Sources List [NI]"
else
	echo "3. Backup Sources List"
	BACK_SRC="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-masterbackup") ]]; then
	echo "4. Backup all three above [NI]"
else
	echo "4. Backup all three above"
	BACK_M="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-debrestore") ]]; then
	echo "5. Restore Debian Packages [NI]"
else
	echo "5. Restore Debian Packages"
	RESTORE_DEB="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-prefrestore") ]]; then
	echo "6. Restore Preference Files [NI]"
else
	echo "6. Restore Preference Files"
	RESTORE_PREF="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-sourcerestore") ]]; then
	echo "7. Restore Sources List [NI]"
else
	echo "7. Restore Sources List"
	RESTORE_SRC="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-masterrestore") ]]; then
	echo "8. Restore all three above [NI]"
else
	echo "8. Restore all three above"
	RESTORE_M="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-cydiafixer") ]]; then
	echo "9. Fix Cydia Crash [NI]"
else
	echo "9. Fix Cydia Crash"
	FIX_CYDIA="installed"
fi
if [[ -z $(dpkg -l|grep "com.nvtechnology.neonutil-extload") ]]; then
	extload="notinstalled"
else
	echo "10. Others (Extensions)"
fi
echo ""
echo -en "Option: "
read selected
if [ $selected == "10" ]; then
	if [[ $BACK_DEB == "notinstalled" ]]; then
		echo "No such option."
	else
		$ROOT/extload
	fi
elif [ $selected == "1" ]; then
	if [[ $BACK_DEB == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "2" ]; then
	if [[ $BACK_PREF == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "3" ]; then
	if [[ $BACK_SRC == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "4" ]; then
	if [[ $BACK_M == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "5" ]; then
	if [[ $RESTORE_DEB == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "6" ]; then
	if [[ $RESTORE_PREF == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "7" ]; then
	if [[ $RESTORE_SRC == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "8" ]; then
	if [[ $RESTORE_M == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
elif [ $selected == "9" ]; then
	if [[ $FIX_CYDIA == "notinstalled" ]]; then
		echo "Unable to execute. Plugin is not installed."
	else
		$ROOT/sload $selected
	fi
else
	echo "No such option."
fi
