#!/bin/bash
name=$1
interaction=$2
if [[ $interaction ]]; then
	if [[ $name ]]; then
		echo "1/5: Running Preference backup..."
		/lib410/Resources/neon/plugins/exec/backup_pref $name --nointeraction
		echo "2/5: Running Source list backup..."
		/lib410/Resources/neon/plugins/exec/backup_source $name --nointeraction
		echo "3/5: Running Source deb backup..."
		/lib410/Resources/neon/plugins/exec/backup_deb $name --nointeraction
		echo "4/5: Compressing..."
		mkdir /private/var/mobile/neonutil_backups/m
		mv /private/var/mobile/neonutil_backups/$name.nprefbackup /private/var/mobile/neonutil_backups/m/$name.nprefbackup
		mv /private/var/mobile/neonutil_backups/$name.nsrcbackup /private/var/mobile/neonutil_backups/m/$name.nsrcbackup
		mv /private/var/mobile/neonutil_backups/$name.ndebbackup /private/var/mobile/neonutil_backups/m/$name.ndebbackup
		cd /private/var/mobile/neonutil_backups
		zip -rqq $name.nmasbackup m
		mv $name.nmasbackup /private/var/mobile/neonutil_backups/$name.nmasbackup
		echo "5/5: Cleaning up..."
		rm -r /private/var/mobile/neonutil_backups/m
		echo "Done."
	else
		echo "Error:"
		echo "Process backup_master returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [[ -z $name ]]; then
		echo "Name cannot be empty!"
	else
		echo "1/5: Running Preference backup..."
		/lib410/Resources/neon/plugins/exec/backup_pref $name --nointeraction
		echo "2/5: Running Source list backup..."
		/lib410/Resources/neon/plugins/exec/backup_source $name --nointeraction
		echo "3/5: Running Source deb backup..."
		/lib410/Resources/neon/plugins/exec/backup_deb $name --nointeraction
		echo "4/5: Compressing..."
		mkdir /private/var/mobile/neonutil_backups/m
		mv /private/var/mobile/neonutil_backups/$name.nprefbackup /private/var/mobile/neonutil_backups/m/$name.nprefbackup
		mv /private/var/mobile/neonutil_backups/$name.nsrcbackup /private/var/mobile/neonutil_backups/m/$name.nsrcbackup
		mv /private/var/mobile/neonutil_backups/$name.ndebbackup /private/var/mobile/neonutil_backups/m/$name.ndebbackup
		cd /private/var/mobile/neonutil_backups
		zip -rqq $name.nmasbackup m
		mv $name.nmasbackup /private/var/mobile/neonutil_backups/$name.nmasbackup
		echo "5/5: Cleaning up..."
		rm -r /private/var/mobile/neonutil_backups/m
		echo "Done."
	fi
fi
