#!/bin/bash
override=$1
log=/lib410/Resources/neon/plugins/log-debcloner
abortrecord=/lib410/Resources/neon/plugins/abortlog-debcloner
declare -i limit=$(</lib410/Preferences/neon/debcloner_extractLimit)
echo "QUERY_PKGS_INSTALLED">$log
total=$(dpkg --get-selections | awk '{print $1}'|grep -v gsc|grep -v "^cy+" | wc -l)
function extract {
	echo "START_EXTRACION">$log
	echo "  Start extraction."
	echo "  Extraction: 0%"
	declare -i previousVal=0
	for ((i=0; i<total; i++)) do
		echo "EXTRACT_"$total"TH_PKG">$log
		( echo y
		echo $i
		 ) | /lib410/Resources/neon/plugins/exec/extract_deb >&- 2>&-
		rm /lib410/Resources/neon/plugins/log-debextraction
		percent=$(awk "BEGIN { pc=100*${i}/${total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
		if [ $percent -ne $previousVal ]; then
			echo "REFRESH_DISPLAYING_PERCENTAGE">$log
			echo "  Extraction: "$percent"%"
			previousVal=$percent
		fi
	done
	echo "EXTRACTION_COMPLETE">$log
	echo "  Extraction: ["$total"/"$total"]"
	echo "  Extraction complete."
	rm $log
}

echo "  Found " $total " debs installed."
if [ $total == 0 ]; then
	echo "  Error:"
	echo "  Process clone_deb returned an error."
	echo "  Installed debs cannot be 0."
	echo "  Handler:"
	echo "  Restarting Query in 5 seconds..."
	sleep 5
	echo "RETRY_QUERY_PKGS_INSTALLED">$log
	total=$(dpkg --get-selections | awk '{print $1}'|grep -v gsc|grep -v "^cy+" | wc -l)
	echo "  Found " $total " debs to extract."
	if [ $total == 0 ]; then
		echo "  Error:"
		echo "  Process clone_deb returned an error."
		echo "  Installed debs cannot be 0. Terminating..."
		rm $log
		exit
	fi
fi
if [ $total -gt $limit ]; then
	if [[ -z $override ]]; then
		echo "Unable to continue."
		echo "Reason: ReachedDeviceOverloadLimit"
		echo "Limit: "$limit
		echo "Due to prevent the overload and reboot of the device, the cloning process is terminated."
		rm $log
		echo "REACHED_LIMIT" > $abortrecord
	else
		extract
	fi
else
	extract
fi
