#!/bin/bash
nointeraction=$1
if [[ $nointeraction == "--nointeraction" ]]; then
	echo "Running without interaction with user."
	echo "This process WILL NOT delete installed tweaks and sources."
	echo "This will not backup tweaks and source lists."
	if [ -e /var/mobile/Library/Cydia ]; then
		rm -r /var/mobile/Library/Cydia
	else
		echo "metadata.cb0 not found."
	fi
	if [ -e /var/mobile/Library/Caches/com.saurik.Cydia ]; then
		rm /var/mobile/Library/Caches/com.saurik.Cydia
	else
		echo "Cache not found."
	fi
	echo "Basic Cydia cache is cleaned."
	echo "This will restart the device in 5 seconds."
	echo "Please rejailbreak after reboot."
	echo "If you want to cancel the reboot, please press ctrl + c."
	sleep 5
	reboot
else
	echo "This process WILL NOT delete installed tweaks and sources."
	echo "Delete metadata.cb0?"
	echo -ne "y/n: "
	read yn
	if [ $yn == "y" ]; then
		if [ -e /var/mobile/Library/Cydia ]; then
			rm -r /var/mobile/Library/Cydia
		else
			echo "metadata.cb0 not found."
		fi
	elif [ $yn == "n" ]; then
		echo "Aborted."
	else
		echo "No such option."
	fi
	echo "Delete /var/mobile/Library/Caches/com.saurik.Cydia?"
	echo -ne "y/n: "
	read yn
	if [ $yn == "y" ]; then
		if [ -e /var/mobile/Library/Caches/com.saurik.Cydia ]; then
			rm /var/mobile/Library/Caches/com.saurik.Cydia
		else
			echo "Cache not found."
		fi
	elif [ $yn == "n" ]; then
		echo "Aborted."
	else
		echo "No such option."
	fi
fi