#!/bin/bash
STORAGE=/lib410/Resources/neon/temp/deb-backup
if [ -e $STORAGE/com.saurik.* ]; then
	rm $STORAGE/com.saurik.*
fi
echo "  Filter: Removed Saurik Packages"
if [ -e $STORAGE/com.ex.substitute* ]; then
	rm $STORAGE/com.ex.substitute*
fi
echo "  Filter: Removed Substitute (If exists)"
if [ -e $STORAGE/*dpkg* ]; then
	rm $STORAGE/*dpkg*
fi
echo "  Filter: Removed DPKG (If exists)"
if [ -e $STORAGE/*apt* ]; then
	rm $STORAGE/*apt*
fi
echo "  Filter: Removed APT Packages (If exists)"
if [ -e $STORAGE/*icleaner* ]; then
	rm $STORAGE/*icleaner*
fi
echo "  Filter: Removed iCleaner (Restore not supported)"
if [ -e $STORAGE/*sileo* ]; then
	rm $STORAGE/*sileo*
fi
echo "  Filter: Removed Sileo (If exists)"
if [ -e $STORAGE/*sileo* ]; then
	rm $STORAGE/*sileo*
fi
echo "  Filter: Removed Sileo (If exists)"
if [ -e $STORAGE/com.nvtechnology.neonutil* ]; then
	rm $STORAGE/com.nvtechnology.neonutil*
fi
echo "  Filter: Removed Neon Utility & plugins"
echo "  Filter: Done"