#!/bin/bash
name=$1
interaction=$2
if [ ! -e /lib410/Resources/neon/temp/master-backup ]; then
	mkdir /lib410/Resources/neon/temp/master-backup
fi
if [[ $interaction ]]; then
	if [[ $name ]]; then
		if [ -e /private/var/mobile/neonutil_backups/$name.nmasbackup ]; then
			echo "1/5: Copying backup file..."
			cp /private/var/mobile/neonutil_backups/$name.nmasbackup /lib410/Resources/neon/temp/master-backup/backup.zip
			echo "2/5: Unpacking backup file..."
			cd /lib410/Resources/neon/temp/master-backup/
			unzip -qq backup.zip
			echo "3/5: Moving each image to place..."
			mv /lib410/Resources/neon/temp/master-backup/m/$name.nprefbackup /private/var/mobile/neonutil_backups/$name.nprefbackup
			mv /lib410/Resources/neon/temp/master-backup/m/$name.nsrcbackup /private/var/mobile/neonutil_backups/$name.nsrcbackup
			mv /lib410/Resources/neon/temp/master-backup/m/$name.ndebbackup /private/var/mobile/neonutil_backups/$name.ndebbackup
			echo "4/5: Restoring sources list..."
			/lib410/Resources/neon/plugins/exec/restore_source $name --nointeraction
			echo "5/5: Restoring preference list..."
			/lib410/Resources/neon/plugins/exec/restore_pref $name --nointeraction -noRespring
			echo "6/5: Cleaning up..."
			/lib410/Resources/neon/cleanup master
			rm /private/var/mobile/neonutil_backups/$name.nsrcbackup
			rm /private/var/mobile/neonutil_backups/$name.nprefbackup
			echo "7/5: Restoring debs..."
			/lib410/Resources/neon/plugins/exec/restore_deb $name --nointeraction
		else
			echo "Error:"
			echo "Process restore_master returned error."
			echo "No such backup found."
		fi
	else
		echo "Error:"
		echo "Process restore_master returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [ -e /private/var/mobile/neonutil_backups/$name.nmasbackup ]; then
		echo "1/5: Copying backup file..."
			cp /private/var/mobile/neonutil_backups/$name.nmasbackup /lib410/Resources/neon/temp/master-backup/backup.zip
			echo "2/5: Unpacking backup file..."
			cd /lib410/Resources/neon/temp/master-backup/
			unzip -qq backup.zip
			echo "3/5: Moving each image to place..."
			mv /lib410/Resources/neon/temp/master-backup/m/$name.nprefbackup /private/var/mobile/neonutil_backups/$name.nprefbackup
			mv /lib410/Resources/neon/temp/master-backup/m/$name.nsrcbackup /private/var/mobile/neonutil_backups/$name.nsrcbackup
			mv /lib410/Resources/neon/temp/master-backup/m/$name.ndebbackup /private/var/mobile/neonutil_backups/$name.ndebbackup
			echo "4/5: Restoring sources list..."
			/lib410/Resources/neon/plugins/exec/restore_source $name --nointeraction
			echo "5/5: Restoring preference list..."
			/lib410/Resources/neon/plugins/exec/restore_pref $name --nointeraction -noRespring
			echo "6/5: Cleaning up..."
			/lib410/Resources/neon/cleanup master
			rm /private/var/mobile/neonutil_backups/$name.nsrcbackup
			rm /private/var/mobile/neonutil_backups/$name.nprefbackup
			echo "7/5: Restoring debs..."
			/lib410/Resources/neon/plugins/exec/restore_deb $name --nointeraction
	else
		echo "Error:"
		echo "Process restore_master returned error."
		echo "No such backup found."
	fi
fi
