#!/bin/bash
backupStyle=$1
if [ $backupStyle == "debian" ]; then
	rm -r /lib410/Resources/neon/temp
	mkdir /lib410/Resources/neon/temp
elif [ $backupStyle == "pref" ]; then
	rm -r /lib410/Resources/neon/temp
	mkdir /lib410/Resources/neon/temp
elif [ $backupStyle == "src" ]; then
	rm -r /lib410/Resources/neon/temp
	mkdir /lib410/Resources/neon/temp
elif [ $backupStyle == "master" ]; then
	rm -r /lib410/Resources/neon/temp
	mkdir /lib410/Resources/neon/temp
else
	echo "Error:"
	echo "Process 'cleanup' returned error."
	echo $backupStyle "is not a supported backup style."
fi
