#!/bin/bash
ROOT=/lib410/Resources/neon/plugins/exec
OPTION=$1
args=$2
if [ $OPTION == "1" ]; then
	$ROOT/backup_deb $args $interaction $coredirect
elif [ $OPTION == "2" ]; then
	$ROOT/backup_pref $args $interaction $coredirect
elif [ $OPTION == "5" ]; then
	$ROOT/restore_deb $args $interaction $coredirect
elif [ $OPTION == "6" ]; then
	$ROOT/restore_pref $args $interaction $coredirect
elif [ $OPTION == "9" ]; then
	$ROOT/cydiafixer --nointeraction
elif [ $OPTION == "4" ]; then
	$ROOT/backup_master $args $interaction $coredirect
elif [ $OPTION == "8" ]; then
	$ROOT/restore_master $args $interaction $coredirect
elif [ $OPTION == "3" ]; then
	$ROOT/backup_source $args $interaction $coredirect
elif [ $OPTION == "7" ]; then
	$ROOT/restore_source $args $interaction $coredirect
else
	echo "Error:"
	echo "Process 'querynlink' returned error."
	echo $OPTION "is not a supported plugin."
fi