#!/bin/bash
name=$1
interaction=$2
echo "This will only backup tweak setups in /var/mobile/Library/Preferences."
if [[ $interaction ]]; then
	if [[ $name ]]; then
		echo "1/[r]: Copying Preference files..."
		/lib410/Resources/neon/plugins/exec/clone_pref
		echo "2/[r]: Filtering..."
		/lib410/Resources/neon/plugins/exec/filter_pref
		echo "3/[r]: Compressing..."
		zip -rqq /private/var/mobile/neonutil_backups/$name.nprefbackup /lib410/Resources/neon/temp/pref-backup
		echo "4/[r]: Cleaning up..."
		/lib410/Resources/neon/cleanup pref
		echo "Done."
	else
		echo "Error:"
		echo "Process backup_pref returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [[ -z $name ]]; then
		echo "Name cannot be empty!"
	else
		echo "1/[r]: Copying Preference files..."
		/lib410/Resources/neon/plugins/exec/clone_pref
		echo "2/[r]: Filtering..."
		/lib410/Resources/neon/plugins/exec/filter_pref
		echo "3/[r]: Compressing..."
		zip -rqq /private/var/mobile/neonutil_backups/$name.nprefbackup /lib410/Resources/neon/temp/pref-backup
		echo "4/[r]: Cleaning up..."
		/lib410/Resources/neon/cleanup pref
		echo "Done."
	fi
fi
