#!/bin/bash
name=$1
interaction=$2
if [[ $interaction ]]; then
	if [[ $name ]]; then
		if [ -e /private/var/mobile/neonutil_backups/$name.ndebbackup ]; then
			echo "1/6: Copying backup file..."
			cp /private/var/mobile/neonutil_backups/$name.ndebbackup /lib410/Resources/neon/temp/deb-backup/backup.zip
			echo "2/6: Unpacking backup file..."
			unzip -rqq /lib410/Resources/neon/temp/deb-backup/backup.zip
			echo "3/6: Installing debs using dpkg..."
			dpkg -i /lib410/Resources/neon/temp/deb-backup/*.deb
			echo "4/6: Cleaning up..."
			/lib410/Resources/neon/cleanup debian
			echo "5/6: Running UICache..."
			uicache
			echo "6/6: Respring in 5 seconds..."
			killall SpringBoard
		else
			echo "Error:"
			echo "Process restore_deb returned error."
			echo "No such backup found."
		fi
	else
		echo "Error:"
		echo "Process restore_deb returned error."
		echo "--nointeraction option requires second argument, which is the name of the backup."
	fi
else
	echo "What is the name of the backup?"
	read name
	if [[ -z $name ]]; then
		echo "Name cannot be empty!"
	else
		if [ -e /private/var/mobile/neonutil_backups/$name.ndebbackup ]; then
			echo "1/6: Copying backup file..."
			cp /private/var/mobile/neonutil_backups/$name.ndebbackup /lib410/Resources/neon/temp/deb-backup/backup.zip
			echo "2/6: Unpacking backup file..."
			unzip -rqq /lib410/Resources/neon/temp/deb-backup/backup.zip
			echo "3/6: Installing debs using dpkg..."
			dpkg -i /lib410/Resources/neon/temp/deb-backup/*.deb
			echo "4/6: Cleaning up..."
			/lib410/Resources/neon/cleanup debian
			echo "5/6: Running UICache..."
			uicache
			echo "6/6: Respring in 5 seconds..."
			killall SpringBoard
		else
			echo "Error:"
			echo "Process restore_deb returned error."
			echo "No such backup found."
		fi
	fi
fi
