#!/bin/bash
total=$(dpkg --get-selections | awk '{print $1}'|grep -v gsc|grep -v "^cy+" | wc -l)
echo "  Found " $total " debs to extract."
echo "  Start extraction."
echo "Extraction: 0%"
for ((i=0; i<total; i++)) do
	( echo y
	echo $i
	 ) | /lib410/Resources/neon/plugins/exec/extract_deb >&- 2>&-
	previousVal=0
	percent=$(awk "BEGIN { pc=100*${i}/${total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
	if [ $percent != $previousVal ]; then
		echo "Extraction: "$percent"%"
		previousVal=$percent
	fi
done
echo "Extraction: ["$total"/"$total"]"